### ISSUE TITLE
[ENHANCEMENT] Not able to insert newline in the title text field

### ISSUE THREAD

**Issue by pathakshashank17** [rutikwankhade/CoverView#4]
It would be nice to be able to type in a new line in the title. This would allow higher customization of the cover image, also, would allow the image to be used elsewhere (apart from covers). Not quite sure if this would be an enhancement or not, but I feel it would be, so adding the **enhancement** title. What do you think? 🤔

**Comment by rutikwankhade** [comment]
Hi! @pathakshashank17 You are right. But don't you think that will divert the sole purpose of this project. The ideal length of a blog title is around 70 characters. That's why I made it this way. I thought of adding a new input for a subtitle but it didn't look good.
The motive is to make this tool clean and minimal.

**Comment by pathakshashank17** [comment]
Got it 👍. Closing this issue.
